jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install --no-transfer-progress --batch-mode --settings etc/settings.xml
        -Dfmt.skip=true
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      if: github.repository_owner == 'knowm'
      name: Deploy with Maven
      run: mvn clean deploy --no-transfer-progress --batch-mode --settings etc/settings.xml
        -Dfmt.skip=true;
name: Java CI with Maven on Push
on:
  repository_dispatch:
    types: trigger-ga___maven_on_push.yml
