jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean verify --no-transfer-progress --batch-mode --settings etc/settings.xml
        -Dmaven.javadoc.skip=true -Dfmt.skip=true;
name: Java CI with Maven on Pull Request
on:
  repository_dispatch:
    types: trigger-ga___maven_on_pull_request.yml
